### ISSUE TITLE
How to connect clients when IDP doesn't allow custom clientId's

### ISSUE THREAD

**Issue by stijnbrouwers** [owncloud/openidconnect#196]
I have done the complete setup for OpenID Connect to my IDP (AWS Cognito) which works like a charm when logging in with the browser.
I also setup service discovery as described in the documentation: https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#set-up-service-discovery
When using the mobile app or Desktop app, they successfully discover OpenID is enabled and open up a browser to login.

But this is where things go wrong. I get an error, which is normal since the clientID/clientSecret combination of the client as described [here](https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#client-ids-secrets-and-redirect-uris) are not known to my IDP. The simple reason I can't resolve this, is because my IDP (AWS Cognito) doesn't allow a custom Client ID when creating an app client (and I think it's the same use case when using Azure AD). They are always generated and cannot be edited.

Can this be resolved in some way? And if so, how? 
Is there any documentation on this?

**Comment by DeepDiver1975** [comment]
> Can this be resolved in some way? And if so, how?

One option is to use dynamic client registration which is partially available already on the individual clients.
If this is not possible you would need to build your own clients to get your specific client id/ secret into these clients.
Not the most convenient approach but no other option :shrug:

**Comment by stijnbrouwers** [comment]
@DeepDiver1975 

Thanks for your quick response!
Option 1: I understand. It's a feature that some IDP's provide (which is not the case for AWS if I'm not mistaking). The OwnCloud features support it and if my IDP should provide it, it would work "automatically".
Option 2: I'm not sure I understand. Do you mean: You can't use the official clients and need to build your own iOS, Android, Desktop apps? Or that I need to create some kind of wrapper around the OwnCloud clients that do some kind of clientid/secret mapping?

**Comment by DeepDiver1975** [comment]
> Option 1: I understand. It's a feature that some IDP's provide (which is not the case for AWS if I'm not mistaking). The OwnCloud features support it and if my IDP should provide it, it would work "automatically".

yes



> Option 2: I'm not sure I understand. Do you mean: You can't use the official clients and need to build your own iOS, Android, Desktop apps? Or that I need to create some kind of wrapper around the OwnCloud clients that do some kind of clientid/secret mapping?

As of today client id and secret are compiled into the code base of desktop client and the mobile apps. So if you cannot use dynamic client registration or the hard coded "default" credential you are doomed to recompile the clients yourself. This is then classic open source business - get the code and compile yourself ;-)

For enterprise customers this is something which is handled within the enterprise edition/subscription ..... 

I understand that this is not the most optimal situation for the community - but open id is currently considered as a feature which is mainly of interest for enterprises.

**Comment by stijnbrouwers** [comment]
Ah ok, that's actually extremely stupid of me not to think of this solution :-)

I think it's acceptable since I know you can set your own download links for the clients through the config.php file.
This way we can point to the custom compiled versions with our credentials.

Thanks for your help!

**Comment by micolous** [comment]
The simpler way around all of this is to install the [OAuth2 app](https://marketplace.owncloud.com/apps/oauth2), and **do not** setup a rewrite rule for OpenID discovery (`/.well-known/openid-configuration`) – **contrary** to [what the OIDC documentation suggests](https://doc.owncloud.com/server/10.14/admin_manual/configuration/user/oidc/oidc.html#set-up-service-discovery).

[The clients will try to authenticate first with OIDC, then OAuth2, then basic auth](https://doc.owncloud.com/ios-app/12.2/appendices/mdm.html#connection-authentication-security).

It'll always to use the hard coded client IDs/secrets with OpenID and OAuth2, unless you've rebuilt those from source or have an MDM policy in place (iOS only).

When you have the ownCloud OAuth2 app installed and no OpenID discovery document, then the clients will authenticate with ownCloud Server as an OAuth2 provider with their hard-coded client IDs/secrets, which are loaded into ownCloud by default.

When those clients open up the browser for consent confirmation, users will be prompted to log in to ownCloud Server from the browser, if they're not already. OIDC with an external IDP and your own client ID/secret from the browser works just fine.

There are some benefits to doing all the consent management for desktop/mobile clients from your IDP (rather than using ownCloud as an OAuth2 provider, as I describe here), but you'd also need to ship your own builds of those clients or otherwise be able to configure custom secrets to be able to fully realise them.
