### ISSUE TITLE
Import non-existing user from provider on login

### ISSUE THREAD

**Issue by moddavid** [owncloud/openidconnect#67]
Knowing OpenID Connect integrations from other software products, I'm confused of the "User with $email is not known." message when a user tries to login through the provider, which does not exist in the owncloud instance so far.

Is this something that will change later?

**Comment by michaelstingl** [comment]
> Is this something that will change later?

@moddavid assumption with the current implementation is, users already exist, from sync with LDAP for example.

Automagically creating new users from OpenID Connect is not implemented yet, but could follow at a later stage. No ETA. (similar to ["Autoprovision Users" mode](https://doc.owncloud.com/server/10.4/admin_manual/enterprise/user_management/user_auth_shibboleth.html#choosing-the-app-mode) with Shibboleth/SAML)

**Comment by moddavid** [comment]
But why should one handle the login via OpenID Connect when LDAP is already in place and running?

**Comment by DeepDiver1975** [comment]
> But why should one handle the login via OpenID Connect when LDAP is already in place and running?

OpenID Connect providers offer admin much more control over the connected system and a central place to manage access to these connected systems.

Because OpenID Connect cannot provide any information about user and group relationships this LDAP integration is required.

If you want to run ownCloud with OpenID Connect but no LDAP please make sure that you manually create the users in owncloud. Never the less you need to take care of the mapping.
